// <auto-generated />
using System;
using Maliev.PerformanceService.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Maliev.PerformanceService.Infrastructure.Migrations
{
    [DbContext(typeof(PerformanceDbContext))]
    [Migration("20251229061906_InitialPerformanceCreate")]
    partial class InitialPerformanceCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Maliev.PerformanceService.Domain.Entities.Goal", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime?>("CompletionDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completion_date");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_date");

                    b.Property<int>("CurrentStatus")
                        .HasColumnType("integer")
                        .HasColumnName("current_status");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<Guid>("EmployeeId")
                        .HasColumnType("uuid")
                        .HasColumnName("employee_id");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modified_date");

                    b.Property<Guid?>("PerformanceReviewId")
                        .HasColumnType("uuid")
                        .HasColumnName("performance_review_id");

                    b.Property<string>("ProgressUpdates")
                        .HasColumnType("text")
                        .HasColumnName("progress_updates");

                    b.Property<string>("SuccessCriteria")
                        .HasColumnType("text")
                        .HasColumnName("success_criteria");

                    b.Property<DateTime>("TargetCompletionDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("target_completion_date");

                    b.HasKey("Id")
                        .HasName("pk_goals");

                    b.HasIndex("CurrentStatus")
                        .HasDatabaseName("idx_goals_status");

                    b.HasIndex("EmployeeId")
                        .HasDatabaseName("idx_goals_employee");

                    b.HasIndex("PerformanceReviewId")
                        .HasDatabaseName("idx_goals_review");

                    b.ToTable("goals", null, t =>
                        {
                            t.HasCheckConstraint("CK_Goal_TargetDate", "target_completion_date > created_date");
                        });
                });

            modelBuilder.Entity("Maliev.PerformanceService.Domain.Entities.PerformanceImprovementPlan", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("CheckInNotes")
                        .HasColumnType("text")
                        .HasColumnName("check_in_notes");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_date");

                    b.Property<Guid>("EmployeeId")
                        .HasColumnType("uuid")
                        .HasColumnName("employee_id");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("end_date");

                    b.Property<int>("ExtensionCount")
                        .HasColumnType("integer")
                        .HasColumnName("extension_count");

                    b.Property<string>("ImprovementAreas")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("improvement_areas");

                    b.Property<Guid>("InitiatorId")
                        .HasColumnType("uuid")
                        .HasColumnName("initiator_id");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modified_date");

                    b.Property<int?>("Outcome")
                        .HasColumnType("integer")
                        .HasColumnName("outcome");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("reason");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("start_date");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<string>("SuccessCriteria")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("success_criteria");

                    b.HasKey("Id")
                        .HasName("pk_performance_improvement_plans");

                    b.HasIndex("EmployeeId")
                        .HasDatabaseName("idx_pips_employee");

                    b.HasIndex("Status")
                        .HasDatabaseName("idx_pips_status");

                    b.ToTable("performance_improvement_plans", null, t =>
                        {
                            t.HasCheckConstraint("CK_PIP_DateRange", "start_date < end_date");
                        });
                });

            modelBuilder.Entity("Maliev.PerformanceService.Domain.Entities.PerformanceReview", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime?>("AcknowledgedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("acknowledged_date");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_date");

                    b.Property<Guid>("EmployeeId")
                        .HasColumnType("uuid")
                        .HasColumnName("employee_id");

                    b.Property<string>("ManagerAssessment")
                        .HasColumnType("text")
                        .HasColumnName("manager_assessment");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modified_date");

                    b.Property<int?>("OverallRating")
                        .HasColumnType("integer")
                        .HasColumnName("overall_rating");

                    b.Property<int>("ReviewCycle")
                        .HasColumnType("integer")
                        .HasColumnName("review_cycle");

                    b.Property<DateTime>("ReviewPeriodEnd")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("review_period_end");

                    b.Property<DateTime>("ReviewPeriodStart")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("review_period_start");

                    b.Property<Guid>("ReviewerId")
                        .HasColumnType("uuid")
                        .HasColumnName("reviewer_id");

                    b.Property<string>("SelfAssessment")
                        .HasColumnType("text")
                        .HasColumnName("self_assessment");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<DateTime?>("SubmittedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("submitted_date");

                    b.HasKey("Id")
                        .HasName("pk_performance_reviews");

                    b.HasIndex("EmployeeId")
                        .HasDatabaseName("idx_perf_reviews_employee");

                    b.HasIndex("ReviewerId")
                        .HasDatabaseName("idx_perf_reviews_reviewer");

                    b.HasIndex("Status")
                        .HasDatabaseName("idx_perf_reviews_status");

                    b.ToTable("performance_reviews", null, t =>
                        {
                            t.HasCheckConstraint("CK_PerformanceReview_Period", "review_period_start < review_period_end");
                        });
                });

            modelBuilder.Entity("Maliev.PerformanceService.Domain.Entities.ReviewFeedback", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_date");

                    b.Property<string>("Feedback")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("feedback");

                    b.Property<int>("FeedbackType")
                        .HasColumnType("integer")
                        .HasColumnName("feedback_type");

                    b.Property<bool>("IsAnonymous")
                        .HasColumnType("boolean")
                        .HasColumnName("is_anonymous");

                    b.Property<Guid>("PerformanceReviewId")
                        .HasColumnType("uuid")
                        .HasColumnName("performance_review_id");

                    b.Property<Guid>("ProviderId")
                        .HasColumnType("uuid")
                        .HasColumnName("provider_id");

                    b.Property<DateTime>("SubmittedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("submitted_date");

                    b.HasKey("Id")
                        .HasName("pk_review_feedback");

                    b.HasIndex("PerformanceReviewId")
                        .HasDatabaseName("idx_feedback_review");

                    b.ToTable("review_feedback", (string)null);
                });

            modelBuilder.Entity("Maliev.PerformanceService.Domain.Entities.Goal", b =>
                {
                    b.HasOne("Maliev.PerformanceService.Domain.Entities.PerformanceReview", null)
                        .WithMany()
                        .HasForeignKey("PerformanceReviewId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_goals_performance_reviews_performance_review_id");
                });

            modelBuilder.Entity("Maliev.PerformanceService.Domain.Entities.ReviewFeedback", b =>
                {
                    b.HasOne("Maliev.PerformanceService.Domain.Entities.PerformanceReview", null)
                        .WithMany()
                        .HasForeignKey("PerformanceReviewId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_review_feedback_performance_reviews_performance_review_id");
                });
#pragma warning restore 612, 618
        }
    }
}
